//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Class
    {
        public string malop { get; set; }
        public string tenlop { get; set; }
        public string maphongban { get; set; }
        public int siso { get; set; }
    
        public virtual Department Department { get; set; }
    }
}
